/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00210a",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#91db2a",
        "on-secondary-container": "#663500",
        "secondary-fixed-dim": "#ffb77d",
        "surface-tint": "#006d30",
        "on-primary-container": "#d3ffd5",
        "primary": "#00652c",
        "secondary": "#904d00",
        "error-container": "#ffdad6",
        "inverse-surface": "#233144",
        "background": "#f8f9ff",
        "tertiary": "#3b6100",
        "on-surface-variant": "#3f493f",
        "on-secondary-fixed": "#2f1500",
        "tertiary-container": "#4d7c00",
        "surface-container": "#e6eeff",
        "on-tertiary": "#ffffff",
        "on-surface": "#0d1c2e",
        "surface-variant": "#d5e3fc",
        "on-tertiary-fixed": "#102000",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#79db8d",
        "primary-container": "#15803d",
        "surface-container-highest": "#d5e3fc",
        "inverse-on-surface": "#eaf1ff",
        "on-background": "#0d1c2e",
        "secondary-container": "#fe932c",
        "primary-fixed-dim": "#79db8d",
        "on-secondary-fixed-variant": "#6e3900",
        "on-tertiary-fixed-variant": "#304f00",
        "outline-variant": "#becabc",
        "outline": "#6f7a6e",
        "surface-container-low": "#eff4ff",
        "secondary-fixed": "#ffdcc3",
        "surface": "#f8f9ff",
        "primary-fixed": "#95f8a7",
        "tertiary-fixed": "#acf847",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "surface-container-high": "#dce9ff",
        "surface-dim": "#ccdbf3",
        "on-primary-fixed-variant": "#005323",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#dfffb3",
        "error": "#ba1a1a"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
